version: '3.3'
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/dockerapp/traefik2/traefik.yml:/traefik.yml:ro
      - /mnt/dockerapp/traefik2/configurations:/configurations
      - /mnt/dockerapp/traefik2/acme/acme.json:/acme.json
    environment:
      TZ: America/Sao_Paulo
    networks:
      - proxera
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`proxy.seusite.com`)"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      - "traefik.http.routers.traefik-secure.middlewares=user-auth@file"

networks:
  proxera:
    external: true