version: '3'

networks:
  proxy:
    external: true
  app-network:
    external: false


services:
  db:
    image: mariadb
    container_name: db
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Sao_Paulo
      - MYSQL_ROOT_PASSWORD=suasenha
      - MYSQL_DATABASE=wordpress #optional
      - MYSQL_USER=usuario #optional
      - MYSQL_PASSWORD=suasenha #optional
    volumes:
      - /mnt/dockerapp/dbdata:/var/lib/mysql
      - /mnt/dockerapp/mariadb/my.cnf:/etc/mysql/my.cnf
    ports:
      - 3306:3306
    networks:
      - app-network
    labels:
      - traefik.enable=false 

  wordpress:
    depends_on: 
      - db
    image: wordpress:6.4.2-php8.1-fpm
    ports:
        - '9000:9000'
    container_name: wordpress
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: usuario
      WORDPRESS_DB_PASSWORD: suasenha
      WORDPRESS_DB_NAME: wordpress
      VIRTUAL_HOST: blog.seusite.com

    volumes:
      - /mnt/dockerapp/wordpress:/var/www/html
    networks:
      - app-network 

  webserver:
    depends_on:
      - wordpress
    image: georgjung/nginx-brotli:mainline
    container_name: webserver
    restart: unless-stopped
    ports:
      - "19000:19000"
    labels:
      - traefik.enable=true

      - traefik.http.routers.webserver.rule=Host(`blog.seusite.com`)
      - traefik.http.routers.webserver.entrypoints=https
      - traefik.http.routers.webserver.tls=true
      - traefik.http.routers.webserver.tls.certresolver=letsencrypt
      - traefik.http.services.webserver.loadbalancer.server.port=29000
      - traefik.docker.network=proxy
    
    volumes:
      - /mnt/dockerapp/nginx:/etc/nginx/conf.d
      - /mnt/dockerapp/logs/nginx:/var/log/nginx
      - /mnt/dockerapp/wordpress:/var/www/html
    networks:
      - app-network
      - proxy

volumes:
  wordpress:
  dbdata: